services:
  - type: web
    name: etf-backend
    env: node
    plan: free
    buildCommand: npm install --omit=dev
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false
